#!/usr/bin/env python3
import argparse
import json
from pathlib import Path
from string import Template
import re
import shutil
from datetime import datetime

def slugify(s: str) -> str:
    s = re.sub(r'[^a-zA-Z0-9]+', '-', s).strip('-').lower()
    return s or 'game'

def load_games(path: Path):
    with path.open('r', encoding='utf-8') as f:
        data = json.load(f)
    if isinstance(data, dict) and 'games' in data:
        return data['games']
    if isinstance(data, list):
        return data
    raise ValueError('games.json must be an array or an object with a "games" array')

def build_pages(games, template_str: str, out_dir: Path, cdn_game_base: str, clean: bool, skip_existing: bool):
    out_dir.mkdir(parents=True, exist_ok=True)
    tpl = Template(template_str)

    slugs = set()
    for g in games:
        name = g.get('name') or 'Untitled'
        url = g.get('url') or slugify(name)
        slugs.add(url)

        game_dir = out_dir / url
        game_dir.mkdir(parents=True, exist_ok=True)
        index_file = game_dir / 'index.html'
        if skip_existing and index_file.exists():
            print(f"skip    {url}/index.html (exists)")
            continue

        src = g.get('src') or f"{cdn_game_base.rstrip('/')}/{url}/"
        image = g.get('image') or '/img/placeholder.png'
        # --- START OF CHANGES ---
        description = g.get('description') or 'No description available.'
        controls = g.get('controls') or 'No controls provided.'
        # --- END OF CHANGES ---

        mapping = {
            'title': name,
            'page_title': name,
            'doc_title': f"The Math Hub - {name}",
            'src': src,
            'image': image,
            'url': url,
            # --- START OF CHANGES ---
            'description': description,
            'controls': controls,
            # --- END OF CHANGES ---
        }

        html = tpl.safe_substitute(mapping)
        banner = f"<!-- Generated {datetime.utcnow().isoformat()}Z by The Math Hub for '{url}'. Do not edit this file directly. -->\n"

        with index_file.open('w', encoding='utf-8') as f:
            f.write(banner + html)
        print(f"wrote   {url}/index.html")

    if clean:
        for item in out_dir.iterdir():
            if item.is_dir():
                name = item.name
                if name in ('res', 'templates'):
                    continue
                if name not in slugs:
                    idx = item / 'index.html'
                    if idx.exists():
                        with idx.open('r', encoding='utf-8') as f:
                            head = f.read(200)
                        if head.startswith('<!-- Generated'):
                            shutil.rmtree(item)
                            print(f"cleaned {name}/")

    print("done.")

def main():
    parser = argparse.ArgumentParser(description='Generate static game pages from a template and games.json')
    parser.add_argument('--games', default='client/public/json/games.json', help='Path to games.json (array or { "games": [...] })')
    parser.add_argument('--template', default='client/public/play/gametemplate.html', help='Path to the HTML template file')
    parser.add_argument('--out-dir', default='client/public/play', help='Output base directory (holds one folder per game)')
    parser.add_argument('--cdn-game-base', default='/cdn/g/', help='Base path for the iframe src, e.g. /cdn/g/')
    parser.add_argument('--clean', action='store_true', help='Remove generated game folders not present in games.json')
    parser.add_argument('--skip-existing', action='store_true', help='Skip writing index.html if it already exists')
    args = parser.parse_args()

    template_path = Path(args.template)
    games_path = Path(args.games)
    out_dir = Path(args.out_dir)

    template_str = template_path.read_text(encoding='utf-8')
    games = load_games(games_path)

    build_pages(
        games=games,
        template_str=template_str,
        out_dir=out_dir,
        cdn_game_base=args.cdn_game_base,
        clean=args.clean,
        skip_existing=args.skip_existing,
    )

if __name__ == '__main__':
    main()